### ISSUE TITLE
Connection pool for Redis & Elasticsearch

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kuma-demo#43]
It seems that connections for Redis are created but not reused, they also seems to live long.

I deployed the app on K8S and enabled passive and active healthchecks. Then I run wrk test on backend app that communicated with Redis. Envoy has limit on 1024 connections per destination service. What happened is that backend used all 1024 connections to Redis and then active HC was failing because HC also use the same pool of 1024 connections. Effectively I had to wait for connection to be dropped or kill the pod with backend.

The same thing happened with Elastic although connections to Elastic are closed fairly quickly.

We should introduce connection pools for both dependencies, with connection limit to something about ~100.

**Comment by subnetmarco** [comment]
Is this issue closed with #48 ? @jakubdyszkiewicz @devadvocado

**Comment by devadvocado** [comment]
Let me test Redis but its definitely resolved for Postgres, pooling is working correctly there
